-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."Invoices" add column "sent" boolean
--  not null default 'false';
