version: '3.6'
services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    restart: always
    container_name: db
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  authorizer:
    image: lakhansamani/authorizer:1.1.41
    ports:
    - "3080:3080"
    depends_on:
    - "postgres"
    container_name: authorizer
    environment:
      ENV: development
      DATABASE_TYPE: postgres
      ADMIN_SECRET: secret
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      PORT: 3080
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      AUTHORIZER_URL: "http://localhost:3080"
  graphql-engine:
    image: hasura/graphql-engine:v2.20.0
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    container_name: hasura
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      HASURA_GRAPHQL_JWT_SECRET:  '{"type":"RS256","key":"-----BEGIN RSA PUBLIC KEY-----\nMIIBCgKCAQEAv3YmlmNqfBDJ+RVJm1mCLuxLs7+G/unIoY86uUrJ5UwVWUg5CQAg\nzN5DdNrFSpA6LnABGyxo4xHpLYsK+U/eVcKvey2Hrx+N9coAYK1czdQnZQT+p+N4\nwfm2LwDXNPdEVbrwlpo5OouwokzRDWpXEwBoKIJDAPTl20NC8XqApITTy4NRZLLJ\n44cW/E8M2MK+6OvofuKSRnA2D5t3uMHr97zomb6fsmQ2tCe/7UESKLvk9R9Q2HHi\nzVSEdTafPliUZln8Cknv1enbVBqfgEkGmItWRZA7Y9/cZFgOvvkd05753BHihbob\nfOPxjzYAEbDDThp5qeSxT+mqSz/TGPUP0wIDAQAB\n-----END RSA PUBLIC KEY-----"}'
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: "myadminsecretkey"
volumes:
  db_data: